### ISSUE TITLE
"j" (а не лише "i - C") також є знаменником, який потенційно може бути 0

### ISSUE THREAD

**Issue by ASDjonok** [YuriiChubenko/public-kpi-labs#1]
https://github.com/YuriiChubenko/public-kpi-labs/blob/ffe7428b6fd9104eec2018d9cff3db22d60ac51c/OOP/Lab1/Java1/src/App.java#L27

**Comment by YuriiChubenko** [comment]
Додав обробник такої ситуації. Всередині програми вспливе ArithmeticException, що потім обробиться catch.
