### ISSUE TITLE
Краще перенести у 39-ту строчку (де закриваюча дужка тіла if)

### ISSUE THREAD

**Issue by ASDjonok** [YuriiChubenko/public-kpi-labs#3]
https://github.com/YuriiChubenko/public-kpi-labs/blob/ffe7428b6fd9104eec2018d9cff3db22d60ac51c/OOP/Lab1/Java1/src/App.java#L41

**Comment by YuriiChubenko** [comment]
Код було дещо переписаний, зазначений else більше не потрібний
