### ISSUE TITLE
З точки зору підтримуваності коду, думаю, краще зробити іншу змінну для іншої помилки. Також можна ці дві змінні переіменувати (додати семантику в назви)

### ISSUE THREAD

**Issue by ASDjonok** [YuriiChubenko/public-kpi-labs#4]
https://github.com/YuriiChubenko/public-kpi-labs/blob/ffe7428b6fd9104eec2018d9cff3db22d60ac51c/OOP/Lab1/Java1/src/App.java#L29

**Comment by YuriiChubenko** [comment]
Прибрав подібні змінні взагалі, замінив їх на exception-и
