### ISSUE TITLE
Варто занести під if

### ISSUE THREAD

**Issue by ASDjonok** [YuriiChubenko/public-kpi-labs#5]
https://github.com/YuriiChubenko/public-kpi-labs/blob/ffe7428b6fd9104eec2018d9cff3db22d60ac51c/OOP/Lab1/Java1/src/App.java#L24

**Comment by YuriiChubenko** [comment]
Прирав if взагалі, замість цього там тепер стоїть try. Змінна не проініціалізується якщо перед цим вспиве виключення IllegalArgumentException. Дякую.
